version: '2'

services:

  update:
    image: bizzotech/erpnext:${ERPNEXT_VERSION}
    container_name: erpnext-update
    volumes:
      - './sites:/home/frappe/frappe-bench/sites'
    depends_on:
      - db
    command: update

  db:
    image: mariadb:latest
    container_name: erpnext-db
    volumes:
      - './config/my.cnf:/etc/mysql/conf.d/frappe.cnf'
      - './dataVolume:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=asdfasdfasdf
      - MYSQL_USER=frappe
      - MYSQL_PASSWORD=frappe
      - MYSQL_DATABASE=frappe
